### ISSUE TITLE
program stuck at calculateInverseKinematics

### ISSUE THREAD

**Issue by Yusufma03** [JanMatas/Rainbow_ddpg#2]
Hi, I was trying to run your code but it always stuck during env.step(action), for both main.py and run_demo.py. I identified the root cause is that it took forever for function calculateInverseKinematics to finish in Mico.py (in function compute_ik_poses). Could you help me with this? Thanks!

**Comment by Alchemist77** [comment]
In **Mico.py** file,
 find the this function line and replace this code. (It is problem of reset pose for null space IK, so i removed it)

**def compute_ik_poses(self):
        joint_poses = self.p.calculateInverseKinematics(
            self.armId,
            targetPosition=self.goalPosition,
            targetOrientation=self.p.getQuaternionFromEuler(
                self.goalOrientation),lowerLimits = self.IKInfo["lowerLimits"],upperLimits = self.IKInfo["upperLimits"],jointRanges = self.IKInfo["jointRanges"],solver = self.IKInfo["solver"],jointDamping = self.IKInfo["jointDamping"],endEffectorLinkIndex = self.IKInfo["endEffectorLinkIndex"])
        return joint_poses**
